version: "3.7"
x-logging: &default-logging
  options:
    max-size: "100m"
    max-file: "5"
  driver: json-file
services:
  reverse-proxy:
    image: nginx:latest
    container_name: airbyte-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - oauth
    volumes:
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-http.conf:/etc/nginx/conf.d/http.conf
      # - ./nginx-https.conf:/etc/nginx/conf.d/https.conf
      - ./certs/letsencrypt:/etc/letsencrypt
      - ./certs/certbot:/etc/certbot
    restart: always